/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteImport } from './../node_modules/.pnpm/@salla.sa+twilight-theme-en_d11bed0737af4b92ddc781c90f13c9c2/node_modules/@salla.sa/twilight-theme-engine/.twilight/$locale'
import { Route as carratHomeRouteImport } from './routes/carrat-home'
import { Route as carratAboutRouteImport } from './routes/carrat-about'
import { Route as DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteImport } from './../node_modules/.pnpm/@salla.sa+twilight-theme-en_d11bed0737af4b92ddc781c90f13c9c2/node_modules/@salla.sa/twilight-theme-engine/.twilight/account'
import { Route as carratBespokeRouteImport } from './routes/carrat-bespoke'
import { Route as blogRouteImport } from './routes/blog'
import { Route as brandsRouteImport } from './routes/brands'
import { Route as carratByOrderRouteImport } from './routes/carrat-by-order'
import { Route as cartPageRouteImport } from './routes/cart-page'
import { Route as carratDiamondsRouteImport } from './routes/carrat-diamonds'
import { Route as carratEducationRouteImport } from './routes/carrat-education'
import { Route as carratFaqRouteImport } from './routes/carrat-faq'
import { Route as latestProductsPageRouteImport } from './routes/latest-products-page'
import { Route as logoutRouteImport } from './routes/logout'
import { Route as loyaltyRouteImport } from './routes/loyalty'
import { Route as mostSalesProductsPageRouteImport } from './routes/most-sales-products-page'
import { Route as offersPageRouteImport } from './routes/offers-page'
import { Route as pendingOrdersRouteImport } from './routes/pending-orders'
import { Route as carratPrivacyRouteImport } from './routes/carrat-privacy'
import { Route as carratReturnsRouteImport } from './routes/carrat-returns'
import { Route as searchPageRouteImport } from './routes/search-page'
import { Route as testimonialsRouteImport } from './routes/testimonials'
import { Route as slugDotbrandIdRouteImport } from './routes/$slug.brand-$id'
import { Route as productListRouteImport } from './routes/product-list'
import { Route as pageSingleRouteImport } from './routes/page-single'
import { Route as productSingleRouteImport } from './routes/product-single'
import { Route as slugTagPageRouteImport } from './routes/slug-tag-page'
import { Route as accountDotnotificationsRouteImport } from './routes/account.notifications'
import { Route as accountDotordersRouteImport } from './routes/account.orders'
import { Route as accountDotpending_ordersRouteImport } from './routes/account.pending_orders'
import { Route as accountDotprofileRouteImport } from './routes/account.profile'
import { Route as accountDotsettingsRouteImport } from './routes/account.settings'
import { Route as accountDotwalletRouteImport } from './routes/account.wallet'
import { Route as accountDotwishlistRouteImport } from './routes/account.wishlist'
import { Route as brandsPageRouteImport } from './routes/brands-page'
import { Route as tagsPageRouteImport } from './routes/tags-page'
import { Route as thankyouDotorderIdRouteImport } from './routes/thankyou.$orderId'
import { Route as accountDotordersDotidRouteImport } from './routes/account.orders.$id'
import { Route as blog_DotslugDotaIdRouteImport } from './routes/blog_.$slug.a-$id'
import { Route as blog_DotslugDotcIdRouteImport } from './routes/blog_.$slug.c-$id'
import { Route as blog_DotslugDottagIdRouteImport } from './routes/blog_.$slug.tag-$id'
import { Route as blog_DotauthorDotidRouteImport } from './routes/blog_.author.$id'
import { Route as DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRouteImport } from './../node_modules/.pnpm/@salla.sa+twilight-theme-en_d11bed0737af4b92ddc781c90f13c9c2/node_modules/@salla.sa/twilight-theme-engine/.twilight/redirect.$type.$id'

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteImport.update(
    {
      id: '/{-$locale}',
      path: '/{-$locale}',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const carratHomeRoute = carratHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratAboutRoute = carratAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteImport.update(
    {
      id: '/account',
      path: '/account',
      getParentRoute: () =>
        DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
    } as any,
  )
const carratBespokeRoute = carratBespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blogRoute = blogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const brandsRoute = brandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratByOrderRoute = carratByOrderRouteImport.update({
  id: '/by-order',
  path: '/by-order',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const cartPageRoute = cartPageRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratDiamondsRoute = carratDiamondsRouteImport.update({
  id: '/diamonds',
  path: '/diamonds',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratEducationRoute = carratEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratFaqRoute = carratFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const latestProductsPageRoute = latestProductsPageRouteImport.update({
  id: '/latest-products',
  path: '/latest-products',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const logoutRoute = logoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const loyaltyRoute = loyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const mostSalesProductsPageRoute = mostSalesProductsPageRouteImport.update({
  id: '/most-sales-products',
  path: '/most-sales-products',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const offersPageRoute = offersPageRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const pendingOrdersRoute = pendingOrdersRouteImport.update({
  id: '/pending-orders',
  path: '/pending-orders',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratPrivacyRoute = carratPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const carratReturnsRoute = carratReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const searchPageRoute = searchPageRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const testimonialsRoute = testimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugDotbrandIdRoute = slugDotbrandIdRouteImport.update({
  id: '/$slug/brand-{$id}',
  path: '/$slug/brand-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const productListRoute = productListRouteImport.update({
  id: '/$slug/c{$id}',
  path: '/$slug/c{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const pageSingleRoute = pageSingleRouteImport.update({
  id: '/$slug/page-{$id}',
  path: '/$slug/page-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const productSingleRoute = productSingleRouteImport.update({
  id: '/$slug/p{$id}',
  path: '/$slug/p{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugTagPageRoute = slugTagPageRouteImport.update({
  id: '/$slug/tag-{$id}',
  path: '/$slug/tag-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const accountDotnotificationsRoute = accountDotnotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotordersRoute = accountDotordersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotpending_ordersRoute =
  accountDotpending_ordersRouteImport.update({
    id: '/pending_orders',
    path: '/pending_orders',
    getParentRoute: () =>
      DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
  } as any)
const accountDotprofileRoute = accountDotprofileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotsettingsRoute = accountDotsettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotwalletRoute = accountDotwalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotwishlistRoute = accountDotwishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const brandsPageRoute = brandsPageRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const tagsPageRoute = tagsPageRouteImport.update({
  id: '/tags/$id',
  path: '/tags/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const thankyouDotorderIdRoute = thankyouDotorderIdRouteImport.update({
  id: '/thankyou/$orderId',
  path: '/thankyou/$orderId',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const accountDotordersDotidRoute = accountDotordersDotidRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const blog_DotslugDotaIdRoute = blog_DotslugDotaIdRouteImport.update({
  id: '/blog/$slug/a-{$id}',
  path: '/blog/$slug/a-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blog_DotslugDotcIdRoute = blog_DotslugDotcIdRouteImport.update({
  id: '/blog/$slug/c-{$id}',
  path: '/blog/$slug/c-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blog_DotslugDottagIdRoute = blog_DotslugDottagIdRouteImport.update({
  id: '/blog/$slug/tag-{$id}',
  path: '/blog/$slug/tag-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blog_DotauthorDotidRoute = blog_DotauthorDotidRouteImport.update({
  id: '/blog/author/$id',
  path: '/blog/author/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRouteImport.update(
    {
      id: '/redirect/$type/$id',
      path: '/redirect/$type/$id',
      getParentRoute: () =>
        DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren
  '/{-$locale}/': typeof carratHomeRoute
  '/{-$locale}/about': typeof carratAboutRoute
  '/{-$locale}/account': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  '/{-$locale}/bespoke': typeof carratBespokeRoute
  '/{-$locale}/blog': typeof blogRoute
  '/{-$locale}/brands': typeof brandsRoute
  '/{-$locale}/by-order': typeof carratByOrderRoute
  '/{-$locale}/cart': typeof cartPageRoute
  '/{-$locale}/diamonds': typeof carratDiamondsRoute
  '/{-$locale}/education': typeof carratEducationRoute
  '/{-$locale}/faq': typeof carratFaqRoute
  '/{-$locale}/latest-products': typeof latestProductsPageRoute
  '/{-$locale}/logout': typeof logoutRoute
  '/{-$locale}/loyalty': typeof loyaltyRoute
  '/{-$locale}/most-sales-products': typeof mostSalesProductsPageRoute
  '/{-$locale}/offers': typeof offersPageRoute
  '/{-$locale}/pending-orders': typeof pendingOrdersRoute
  '/{-$locale}/privacy': typeof carratPrivacyRoute
  '/{-$locale}/returns': typeof carratReturnsRoute
  '/{-$locale}/search': typeof searchPageRoute
  '/{-$locale}/testimonials': typeof testimonialsRoute
  '/{-$locale}/$slug/brand-{$id}': typeof slugDotbrandIdRoute
  '/{-$locale}/$slug/c{$id}': typeof productListRoute
  '/{-$locale}/$slug/page-{$id}': typeof pageSingleRoute
  '/{-$locale}/$slug/p{$id}': typeof productSingleRoute
  '/{-$locale}/$slug/tag-{$id}': typeof slugTagPageRoute
  '/{-$locale}/account/notifications': typeof accountDotnotificationsRoute
  '/{-$locale}/account/orders': typeof accountDotordersRoute
  '/{-$locale}/account/pending_orders': typeof accountDotpending_ordersRoute
  '/{-$locale}/account/profile': typeof accountDotprofileRoute
  '/{-$locale}/account/settings': typeof accountDotsettingsRoute
  '/{-$locale}/account/wallet': typeof accountDotwalletRoute
  '/{-$locale}/account/wishlist': typeof accountDotwishlistRoute
  '/{-$locale}/brands/$id': typeof brandsPageRoute
  '/{-$locale}/tags/$id': typeof tagsPageRoute
  '/{-$locale}/thankyou/$orderId': typeof thankyouDotorderIdRoute
  '/{-$locale}/account/orders/$id': typeof accountDotordersDotidRoute
  '/{-$locale}/blog/$slug/a-{$id}': typeof blog_DotslugDotaIdRoute
  '/{-$locale}/blog/$slug/c-{$id}': typeof blog_DotslugDotcIdRoute
  '/{-$locale}/blog/$slug/tag-{$id}': typeof blog_DotslugDottagIdRoute
  '/{-$locale}/blog/author/$id': typeof blog_DotauthorDotidRoute
  '/{-$locale}/redirect/$type/$id': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof carratHomeRoute
  '/{-$locale}/about': typeof carratAboutRoute
  '/{-$locale}/account': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  '/{-$locale}/bespoke': typeof carratBespokeRoute
  '/{-$locale}/blog': typeof blogRoute
  '/{-$locale}/brands': typeof brandsRoute
  '/{-$locale}/by-order': typeof carratByOrderRoute
  '/{-$locale}/cart': typeof cartPageRoute
  '/{-$locale}/diamonds': typeof carratDiamondsRoute
  '/{-$locale}/education': typeof carratEducationRoute
  '/{-$locale}/faq': typeof carratFaqRoute
  '/{-$locale}/latest-products': typeof latestProductsPageRoute
  '/{-$locale}/logout': typeof logoutRoute
  '/{-$locale}/loyalty': typeof loyaltyRoute
  '/{-$locale}/most-sales-products': typeof mostSalesProductsPageRoute
  '/{-$locale}/offers': typeof offersPageRoute
  '/{-$locale}/pending-orders': typeof pendingOrdersRoute
  '/{-$locale}/privacy': typeof carratPrivacyRoute
  '/{-$locale}/returns': typeof carratReturnsRoute
  '/{-$locale}/search': typeof searchPageRoute
  '/{-$locale}/testimonials': typeof testimonialsRoute
  '/{-$locale}/$slug/brand-{$id}': typeof slugDotbrandIdRoute
  '/{-$locale}/$slug/c{$id}': typeof productListRoute
  '/{-$locale}/$slug/page-{$id}': typeof pageSingleRoute
  '/{-$locale}/$slug/p{$id}': typeof productSingleRoute
  '/{-$locale}/$slug/tag-{$id}': typeof slugTagPageRoute
  '/{-$locale}/account/notifications': typeof accountDotnotificationsRoute
  '/{-$locale}/account/orders': typeof accountDotordersRoute
  '/{-$locale}/account/pending_orders': typeof accountDotpending_ordersRoute
  '/{-$locale}/account/profile': typeof accountDotprofileRoute
  '/{-$locale}/account/settings': typeof accountDotsettingsRoute
  '/{-$locale}/account/wallet': typeof accountDotwalletRoute
  '/{-$locale}/account/wishlist': typeof accountDotwishlistRoute
  '/{-$locale}/brands/$id': typeof brandsPageRoute
  '/{-$locale}/tags/$id': typeof tagsPageRoute
  '/{-$locale}/thankyou/$orderId': typeof thankyouDotorderIdRoute
  '/{-$locale}/account/orders/$id': typeof accountDotordersDotidRoute
  '/{-$locale}/blog/$slug/a-{$id}': typeof blog_DotslugDotaIdRoute
  '/{-$locale}/blog/$slug/c-{$id}': typeof blog_DotslugDotcIdRoute
  '/{-$locale}/blog/$slug/tag-{$id}': typeof blog_DotslugDottagIdRoute
  '/{-$locale}/blog/author/$id': typeof blog_DotauthorDotidRoute
  '/{-$locale}/redirect/$type/$id': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren
  '/{-$locale}/': typeof carratHomeRoute
  '/{-$locale}/about': typeof carratAboutRoute
  '/{-$locale}/account': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  '/{-$locale}/bespoke': typeof carratBespokeRoute
  '/{-$locale}/blog': typeof blogRoute
  '/{-$locale}/brands': typeof brandsRoute
  '/{-$locale}/by-order': typeof carratByOrderRoute
  '/{-$locale}/cart': typeof cartPageRoute
  '/{-$locale}/diamonds': typeof carratDiamondsRoute
  '/{-$locale}/education': typeof carratEducationRoute
  '/{-$locale}/faq': typeof carratFaqRoute
  '/{-$locale}/latest-products': typeof latestProductsPageRoute
  '/{-$locale}/logout': typeof logoutRoute
  '/{-$locale}/loyalty': typeof loyaltyRoute
  '/{-$locale}/most-sales-products': typeof mostSalesProductsPageRoute
  '/{-$locale}/offers': typeof offersPageRoute
  '/{-$locale}/pending-orders': typeof pendingOrdersRoute
  '/{-$locale}/privacy': typeof carratPrivacyRoute
  '/{-$locale}/returns': typeof carratReturnsRoute
  '/{-$locale}/search': typeof searchPageRoute
  '/{-$locale}/testimonials': typeof testimonialsRoute
  '/{-$locale}/$slug/brand-{$id}': typeof slugDotbrandIdRoute
  '/{-$locale}/$slug/c{$id}': typeof productListRoute
  '/{-$locale}/$slug/page-{$id}': typeof pageSingleRoute
  '/{-$locale}/$slug/p{$id}': typeof productSingleRoute
  '/{-$locale}/$slug/tag-{$id}': typeof slugTagPageRoute
  '/{-$locale}/account/notifications': typeof accountDotnotificationsRoute
  '/{-$locale}/account/orders': typeof accountDotordersRoute
  '/{-$locale}/account/pending_orders': typeof accountDotpending_ordersRoute
  '/{-$locale}/account/profile': typeof accountDotprofileRoute
  '/{-$locale}/account/settings': typeof accountDotsettingsRoute
  '/{-$locale}/account/wallet': typeof accountDotwalletRoute
  '/{-$locale}/account/wishlist': typeof accountDotwishlistRoute
  '/{-$locale}/brands/$id': typeof brandsPageRoute
  '/{-$locale}/tags/$id': typeof tagsPageRoute
  '/{-$locale}/thankyou/$orderId': typeof thankyouDotorderIdRoute
  '/{-$locale}/account/orders/$id': typeof accountDotordersDotidRoute
  '/{-$locale}/blog/$slug/a-{$id}': typeof blog_DotslugDotaIdRoute
  '/{-$locale}/blog/$slug/c-{$id}': typeof blog_DotslugDotcIdRoute
  '/{-$locale}/blog/$slug/tag-{$id}': typeof blog_DotslugDottagIdRoute
  '/{-$locale}/blog/author/$id': typeof blog_DotauthorDotidRoute
  '/{-$locale}/redirect/$type/$id': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/bespoke'
    | '/{-$locale}/blog'
    | '/{-$locale}/brands'
    | '/{-$locale}/by-order'
    | '/{-$locale}/cart'
    | '/{-$locale}/diamonds'
    | '/{-$locale}/education'
    | '/{-$locale}/faq'
    | '/{-$locale}/latest-products'
    | '/{-$locale}/logout'
    | '/{-$locale}/loyalty'
    | '/{-$locale}/most-sales-products'
    | '/{-$locale}/offers'
    | '/{-$locale}/pending-orders'
    | '/{-$locale}/privacy'
    | '/{-$locale}/returns'
    | '/{-$locale}/search'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/$slug/brand-{$id}'
    | '/{-$locale}/$slug/c{$id}'
    | '/{-$locale}/$slug/page-{$id}'
    | '/{-$locale}/$slug/p{$id}'
    | '/{-$locale}/$slug/tag-{$id}'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/account/pending_orders'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/settings'
    | '/{-$locale}/account/wallet'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/brands/$id'
    | '/{-$locale}/tags/$id'
    | '/{-$locale}/thankyou/$orderId'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/blog/$slug/a-{$id}'
    | '/{-$locale}/blog/$slug/c-{$id}'
    | '/{-$locale}/blog/$slug/tag-{$id}'
    | '/{-$locale}/blog/author/$id'
    | '/{-$locale}/redirect/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/bespoke'
    | '/{-$locale}/blog'
    | '/{-$locale}/brands'
    | '/{-$locale}/by-order'
    | '/{-$locale}/cart'
    | '/{-$locale}/diamonds'
    | '/{-$locale}/education'
    | '/{-$locale}/faq'
    | '/{-$locale}/latest-products'
    | '/{-$locale}/logout'
    | '/{-$locale}/loyalty'
    | '/{-$locale}/most-sales-products'
    | '/{-$locale}/offers'
    | '/{-$locale}/pending-orders'
    | '/{-$locale}/privacy'
    | '/{-$locale}/returns'
    | '/{-$locale}/search'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/$slug/brand-{$id}'
    | '/{-$locale}/$slug/c{$id}'
    | '/{-$locale}/$slug/page-{$id}'
    | '/{-$locale}/$slug/p{$id}'
    | '/{-$locale}/$slug/tag-{$id}'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/account/pending_orders'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/settings'
    | '/{-$locale}/account/wallet'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/brands/$id'
    | '/{-$locale}/tags/$id'
    | '/{-$locale}/thankyou/$orderId'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/blog/$slug/a-{$id}'
    | '/{-$locale}/blog/$slug/c-{$id}'
    | '/{-$locale}/blog/$slug/tag-{$id}'
    | '/{-$locale}/blog/author/$id'
    | '/{-$locale}/redirect/$type/$id'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/about'
    | '/{-$locale}/account'
    | '/{-$locale}/bespoke'
    | '/{-$locale}/blog'
    | '/{-$locale}/brands'
    | '/{-$locale}/by-order'
    | '/{-$locale}/cart'
    | '/{-$locale}/diamonds'
    | '/{-$locale}/education'
    | '/{-$locale}/faq'
    | '/{-$locale}/latest-products'
    | '/{-$locale}/logout'
    | '/{-$locale}/loyalty'
    | '/{-$locale}/most-sales-products'
    | '/{-$locale}/offers'
    | '/{-$locale}/pending-orders'
    | '/{-$locale}/privacy'
    | '/{-$locale}/returns'
    | '/{-$locale}/search'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/$slug/brand-{$id}'
    | '/{-$locale}/$slug/c{$id}'
    | '/{-$locale}/$slug/page-{$id}'
    | '/{-$locale}/$slug/p{$id}'
    | '/{-$locale}/$slug/tag-{$id}'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/account/pending_orders'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/settings'
    | '/{-$locale}/account/wallet'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/brands/$id'
    | '/{-$locale}/tags/$id'
    | '/{-$locale}/thankyou/$orderId'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/blog/$slug/a-{$id}'
    | '/{-$locale}/blog/$slug/c-{$id}'
    | '/{-$locale}/blog/$slug/tag-{$id}'
    | '/{-$locale}/blog/author/$id'
    | '/{-$locale}/redirect/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof carratHomeRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof carratAboutRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/account': {
      id: '/{-$locale}/account'
      path: '/account'
      fullPath: '/{-$locale}/account'
      preLoaderRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/bespoke': {
      id: '/{-$locale}/bespoke'
      path: '/bespoke'
      fullPath: '/{-$locale}/bespoke'
      preLoaderRoute: typeof carratBespokeRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog': {
      id: '/{-$locale}/blog'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof blogRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/brands': {
      id: '/{-$locale}/brands'
      path: '/brands'
      fullPath: '/{-$locale}/brands'
      preLoaderRoute: typeof brandsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/by-order': {
      id: '/{-$locale}/by-order'
      path: '/by-order'
      fullPath: '/{-$locale}/by-order'
      preLoaderRoute: typeof carratByOrderRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/cart': {
      id: '/{-$locale}/cart'
      path: '/cart'
      fullPath: '/{-$locale}/cart'
      preLoaderRoute: typeof cartPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/diamonds': {
      id: '/{-$locale}/diamonds'
      path: '/diamonds'
      fullPath: '/{-$locale}/diamonds'
      preLoaderRoute: typeof carratDiamondsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/education': {
      id: '/{-$locale}/education'
      path: '/education'
      fullPath: '/{-$locale}/education'
      preLoaderRoute: typeof carratEducationRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/faq': {
      id: '/{-$locale}/faq'
      path: '/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof carratFaqRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/latest-products': {
      id: '/{-$locale}/latest-products'
      path: '/latest-products'
      fullPath: '/{-$locale}/latest-products'
      preLoaderRoute: typeof latestProductsPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/logout': {
      id: '/{-$locale}/logout'
      path: '/logout'
      fullPath: '/{-$locale}/logout'
      preLoaderRoute: typeof logoutRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/loyalty': {
      id: '/{-$locale}/loyalty'
      path: '/loyalty'
      fullPath: '/{-$locale}/loyalty'
      preLoaderRoute: typeof loyaltyRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/most-sales-products': {
      id: '/{-$locale}/most-sales-products'
      path: '/most-sales-products'
      fullPath: '/{-$locale}/most-sales-products'
      preLoaderRoute: typeof mostSalesProductsPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/offers': {
      id: '/{-$locale}/offers'
      path: '/offers'
      fullPath: '/{-$locale}/offers'
      preLoaderRoute: typeof offersPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/pending-orders': {
      id: '/{-$locale}/pending-orders'
      path: '/pending-orders'
      fullPath: '/{-$locale}/pending-orders'
      preLoaderRoute: typeof pendingOrdersRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof carratPrivacyRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/returns': {
      id: '/{-$locale}/returns'
      path: '/returns'
      fullPath: '/{-$locale}/returns'
      preLoaderRoute: typeof carratReturnsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/search': {
      id: '/{-$locale}/search'
      path: '/search'
      fullPath: '/{-$locale}/search'
      preLoaderRoute: typeof searchPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/testimonials': {
      id: '/{-$locale}/testimonials'
      path: '/testimonials'
      fullPath: '/{-$locale}/testimonials'
      preLoaderRoute: typeof testimonialsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/brand-{$id}': {
      id: '/{-$locale}/$slug/brand-{$id}'
      path: '/$slug/brand-{$id}'
      fullPath: '/{-$locale}/$slug/brand-{$id}'
      preLoaderRoute: typeof slugDotbrandIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/c{$id}': {
      id: '/{-$locale}/$slug/c{$id}'
      path: '/$slug/c{$id}'
      fullPath: '/{-$locale}/$slug/c{$id}'
      preLoaderRoute: typeof productListRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/page-{$id}': {
      id: '/{-$locale}/$slug/page-{$id}'
      path: '/$slug/page-{$id}'
      fullPath: '/{-$locale}/$slug/page-{$id}'
      preLoaderRoute: typeof pageSingleRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/p{$id}': {
      id: '/{-$locale}/$slug/p{$id}'
      path: '/$slug/p{$id}'
      fullPath: '/{-$locale}/$slug/p{$id}'
      preLoaderRoute: typeof productSingleRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/tag-{$id}': {
      id: '/{-$locale}/$slug/tag-{$id}'
      path: '/$slug/tag-{$id}'
      fullPath: '/{-$locale}/$slug/tag-{$id}'
      preLoaderRoute: typeof slugTagPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/account/notifications': {
      id: '/{-$locale}/account/notifications'
      path: '/notifications'
      fullPath: '/{-$locale}/account/notifications'
      preLoaderRoute: typeof accountDotnotificationsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/orders': {
      id: '/{-$locale}/account/orders'
      path: '/orders'
      fullPath: '/{-$locale}/account/orders'
      preLoaderRoute: typeof accountDotordersRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/pending_orders': {
      id: '/{-$locale}/account/pending_orders'
      path: '/pending_orders'
      fullPath: '/{-$locale}/account/pending_orders'
      preLoaderRoute: typeof accountDotpending_ordersRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/profile': {
      id: '/{-$locale}/account/profile'
      path: '/profile'
      fullPath: '/{-$locale}/account/profile'
      preLoaderRoute: typeof accountDotprofileRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/settings': {
      id: '/{-$locale}/account/settings'
      path: '/settings'
      fullPath: '/{-$locale}/account/settings'
      preLoaderRoute: typeof accountDotsettingsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/wallet': {
      id: '/{-$locale}/account/wallet'
      path: '/wallet'
      fullPath: '/{-$locale}/account/wallet'
      preLoaderRoute: typeof accountDotwalletRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/wishlist': {
      id: '/{-$locale}/account/wishlist'
      path: '/wishlist'
      fullPath: '/{-$locale}/account/wishlist'
      preLoaderRoute: typeof accountDotwishlistRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/brands/$id': {
      id: '/{-$locale}/brands/$id'
      path: '/brands/$id'
      fullPath: '/{-$locale}/brands/$id'
      preLoaderRoute: typeof brandsPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/tags/$id': {
      id: '/{-$locale}/tags/$id'
      path: '/tags/$id'
      fullPath: '/{-$locale}/tags/$id'
      preLoaderRoute: typeof tagsPageRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/thankyou/$orderId': {
      id: '/{-$locale}/thankyou/$orderId'
      path: '/thankyou/$orderId'
      fullPath: '/{-$locale}/thankyou/$orderId'
      preLoaderRoute: typeof thankyouDotorderIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/account/orders/$id': {
      id: '/{-$locale}/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/{-$locale}/account/orders/$id'
      preLoaderRoute: typeof accountDotordersDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/blog/$slug/a-{$id}': {
      id: '/{-$locale}/blog/$slug/a-{$id}'
      path: '/blog/$slug/a-{$id}'
      fullPath: '/{-$locale}/blog/$slug/a-{$id}'
      preLoaderRoute: typeof blog_DotslugDotaIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog/$slug/c-{$id}': {
      id: '/{-$locale}/blog/$slug/c-{$id}'
      path: '/blog/$slug/c-{$id}'
      fullPath: '/{-$locale}/blog/$slug/c-{$id}'
      preLoaderRoute: typeof blog_DotslugDotcIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog/$slug/tag-{$id}': {
      id: '/{-$locale}/blog/$slug/tag-{$id}'
      path: '/blog/$slug/tag-{$id}'
      fullPath: '/{-$locale}/blog/$slug/tag-{$id}'
      preLoaderRoute: typeof blog_DotslugDottagIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog/author/$id': {
      id: '/{-$locale}/blog/author/$id'
      path: '/blog/author/$id'
      fullPath: '/{-$locale}/blog/author/$id'
      preLoaderRoute: typeof blog_DotauthorDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/redirect/$type/$id': {
      id: '/{-$locale}/redirect/$type/$id'
      path: '/redirect/$type/$id'
      fullPath: '/{-$locale}/redirect/$type/$id'
      preLoaderRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
  }
}

interface DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren {
  accountDotnotificationsRoute: typeof accountDotnotificationsRoute
  accountDotordersRoute: typeof accountDotordersRoute
  accountDotpending_ordersRoute: typeof accountDotpending_ordersRoute
  accountDotprofileRoute: typeof accountDotprofileRoute
  accountDotsettingsRoute: typeof accountDotsettingsRoute
  accountDotwalletRoute: typeof accountDotwalletRoute
  accountDotwishlistRoute: typeof accountDotwishlistRoute
  accountDotordersDotidRoute: typeof accountDotordersDotidRoute
}

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren: DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren =
  {
    accountDotnotificationsRoute: accountDotnotificationsRoute,
    accountDotordersRoute: accountDotordersRoute,
    accountDotpending_ordersRoute: accountDotpending_ordersRoute,
    accountDotprofileRoute: accountDotprofileRoute,
    accountDotsettingsRoute: accountDotsettingsRoute,
    accountDotwalletRoute: accountDotwalletRoute,
    accountDotwishlistRoute: accountDotwishlistRoute,
    accountDotordersDotidRoute: accountDotordersDotidRoute,
  }

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute._addFileChildren(
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren,
  )

interface DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren {
  carratHomeRoute: typeof carratHomeRoute
  carratAboutRoute: typeof carratAboutRoute
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  carratBespokeRoute: typeof carratBespokeRoute
  blogRoute: typeof blogRoute
  brandsRoute: typeof brandsRoute
  carratByOrderRoute: typeof carratByOrderRoute
  cartPageRoute: typeof cartPageRoute
  carratDiamondsRoute: typeof carratDiamondsRoute
  carratEducationRoute: typeof carratEducationRoute
  carratFaqRoute: typeof carratFaqRoute
  latestProductsPageRoute: typeof latestProductsPageRoute
  logoutRoute: typeof logoutRoute
  loyaltyRoute: typeof loyaltyRoute
  mostSalesProductsPageRoute: typeof mostSalesProductsPageRoute
  offersPageRoute: typeof offersPageRoute
  pendingOrdersRoute: typeof pendingOrdersRoute
  carratPrivacyRoute: typeof carratPrivacyRoute
  carratReturnsRoute: typeof carratReturnsRoute
  searchPageRoute: typeof searchPageRoute
  testimonialsRoute: typeof testimonialsRoute
  slugDotbrandIdRoute: typeof slugDotbrandIdRoute
  productListRoute: typeof productListRoute
  pageSingleRoute: typeof pageSingleRoute
  productSingleRoute: typeof productSingleRoute
  slugTagPageRoute: typeof slugTagPageRoute
  brandsPageRoute: typeof brandsPageRoute
  tagsPageRoute: typeof tagsPageRoute
  thankyouDotorderIdRoute: typeof thankyouDotorderIdRoute
  blog_DotslugDotaIdRoute: typeof blog_DotslugDotaIdRoute
  blog_DotslugDotcIdRoute: typeof blog_DotslugDotcIdRoute
  blog_DotslugDottagIdRoute: typeof blog_DotslugDottagIdRoute
  blog_DotauthorDotidRoute: typeof blog_DotauthorDotidRoute
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren: DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren =
  {
    carratHomeRoute: carratHomeRoute,
    carratAboutRoute: carratAboutRoute,
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute:
      DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren,
    carratBespokeRoute: carratBespokeRoute,
    blogRoute: blogRoute,
    brandsRoute: brandsRoute,
    carratByOrderRoute: carratByOrderRoute,
    cartPageRoute: cartPageRoute,
    carratDiamondsRoute: carratDiamondsRoute,
    carratEducationRoute: carratEducationRoute,
    carratFaqRoute: carratFaqRoute,
    latestProductsPageRoute: latestProductsPageRoute,
    logoutRoute: logoutRoute,
    loyaltyRoute: loyaltyRoute,
    mostSalesProductsPageRoute: mostSalesProductsPageRoute,
    offersPageRoute: offersPageRoute,
    pendingOrdersRoute: pendingOrdersRoute,
    carratPrivacyRoute: carratPrivacyRoute,
    carratReturnsRoute: carratReturnsRoute,
    searchPageRoute: searchPageRoute,
    testimonialsRoute: testimonialsRoute,
    slugDotbrandIdRoute: slugDotbrandIdRoute,
    productListRoute: productListRoute,
    pageSingleRoute: pageSingleRoute,
    productSingleRoute: productSingleRoute,
    slugTagPageRoute: slugTagPageRoute,
    brandsPageRoute: brandsPageRoute,
    tagsPageRoute: tagsPageRoute,
    thankyouDotorderIdRoute: thankyouDotorderIdRoute,
    blog_DotslugDotaIdRoute: blog_DotslugDotaIdRoute,
    blog_DotslugDotcIdRoute: blog_DotslugDotcIdRoute,
    blog_DotslugDottagIdRoute: blog_DotslugDottagIdRoute,
    blog_DotauthorDotidRoute: blog_DotauthorDotidRoute,
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute:
      DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute,
  }

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute._addFileChildren(
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute:
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_d11bed0737af4b92ddc781c90f13c9c2Node_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
