export { Brands } from './Brands';
export { CustomTestimonials } from './CustomTestimonials';
export { EnhancedSlider } from './EnhancedSlider';
export { FeaturedProducts, featuredProductsConfig } from './FeaturedProducts';
export { FixedProducts } from './FixedProducts';
export { MainLinks } from './MainLinks';
export { PhotosSlider } from './PhotosSlider';
export { ProductsSlider } from './ProductsSlider';
export { SliderProductsWithHeader } from './SliderProductsWithHeader';
export { EnhancedSquareBanners } from './EnhancedSquareBanners';
